<package format="2">
  <name>galbot_zero_description</name>
  <version>1.0.0</version>
  <description>URDF/Xacro description package for Galbot Zero.</description>

  <maintainer email="todo@example.com">TODO</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ocs2_arm_controller</exec_depend>
  <exec_depend>ocs2_wbc_controller</exec_depend>
  <exec_depend>robot_common_launch</exec_depend>
  <exec_depend>basic_joint_controller</exec_depend>
  <exec_depend>component_models</exec_depend>
  <exec_depend>sensor_models</exec_depend>
  <exec_depend>rm75_description</exec_depend>
  <exec_depend>inspire_description</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
