<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="2">
  <name>galbot_s1_description</name>
  <version>1.0.0</version>
  <description>
    URDF / xacro description package for Galbot S1 (layout aligned with galbot_foxtrot_description).
  </description>
  <maintainer email="biao876990970@hotmail.com">Huang Zhenbiao</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>robot_common_launch</exec_depend>
  <exec_depend>sensor_models</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
